#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

define('YS_PATH_BASE',  __DIR__);
define('YS_PATH_APP', YS_PATH_BASE . '/app');
define('YS_PATH_VENDOR', YS_PATH_APP . '/vendor');

require(YS_PATH_VENDOR . '/autoload.php');
require(YS_PATH_APP . '/common/config/env.php');

defined('YII_ENV') || define('YII_ENV', getenv('YII_ENV'));
defined('YII_DEBUG') || define('YII_DEBUG', getenv('YII_DEBUG'));

require(YS_PATH_VENDOR . '/yiisoft/yii2/Yii.php');
require(YS_PATH_APP . '/common/config/bootstrap.php');
require(YS_PATH_APP . '/console/config/bootstrap.php');

$config = \yii\helpers\ArrayHelper::merge(
    require(YS_PATH_APP . '/common/config/main.php'),
    require(YS_PATH_APP . '/common/config/main-'.YII_ENV.'.php'),
    require(YS_PATH_APP . '/console/config/main.php'),
    require(YS_PATH_APP . '/console/config/main-'.YII_ENV.'.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);